import { supabase, ensureAuth } from './supabase.js?v=20261007-1';

const CATEGORIES=['主菜','副菜','汁物','主食','デザート','その他'];
const GENRES=['和食','洋食','中華','韓国','エスニック','その他'];
const SHOPPING_CATEGORIES=['肉・魚・卵','野菜','調味料','乳製品','パン・パスタ・主食','冷凍食品','日用品','その他'];
const DEFAULT_SHOPPING_MASTER=[['肉・魚・卵',['豚こま','鶏もも','鶏むね','豚バラ','ひき肉','卵']],['野菜',['玉ねぎ','にんじん','じゃがいも','キャベツ','ピーマン','きのこ','トマト','レタス']],['調味料',['醤油','みそ','砂糖','塩','こしょう','料理酒','みりん']],['乳製品',['牛乳','ヨーグルト','チーズ']],['パン・パスタ・主食',['食パン','米','パスタ','うどん']],['冷凍食品',['冷凍うどん','冷凍野菜','冷凍食品']],['日用品',['ラップ','キッチンペーパー','ティッシュ','食器用洗剤']],['その他',['納豆','子供のお菓子']]];
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={recipes:[],tags:[],editingId:null,detailId:null,shoppingMaster:[],shoppingList:[],shoppingPendingChanges:new Map(),showPurchased:false};
function loading(v){$('loading').classList.toggle('hidden',!v)}
function toast(m){const e=$('toast');e.textContent=m;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),2200)}
function view(id){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');window.scrollTo({top:0,behavior:'auto'})}
function fillSelect(el,values,first=''){el.innerHTML=(first?`<option value="">${esc(first)}</option>`:'')+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}
function setup(){
 fillSelect($('categoryFilter'),CATEGORIES,'主カテゴリすべて');fillSelect($('genreFilter'),GENRES,'ジャンルすべて');fillSelect($('formCategory'),CATEGORIES);fillSelect($('formGenre'),GENRES);fillSelect($('shoppingInputCategory'),SHOPPING_CATEGORIES);fillSelect($('shoppingMasterInputCategory'),SHOPPING_CATEGORIES);
 $('newRecipeButton').onclick=()=>openForm();$('shoppingButton').onclick=()=>openShopping();$('backFromForm').onclick=$('cancelForm').onclick=()=>view('listView');$('backFromDetail').onclick=()=>view('listView');$('backFromShopping').onclick=()=>view('listView');$('addIngredient').onclick=()=>addIngredientRow();$('addInstruction').onclick=()=>addInstructionRow();$('recipeForm').onsubmit=saveRecipe;$('shoppingFreeForm').onsubmit=addFreeShoppingItem;$('shoppingMasterForm').onsubmit=addShoppingMasterItem;$('addSelectedShopping').onclick=addSelectedShoppingItems;$('showPurchased').onchange=()=>{state.showPurchased=$('showPurchased').checked;renderShoppingList()};$('searchInput').oninput=renderList;['categoryFilter','genreFilter','tagFilter','favoriteFilter'].forEach(id=>$(id).onchange=renderList);$('editRecipe').onclick=()=>state.detailId&&openForm(state.detailId);$('deleteRecipe').onclick=deleteCurrentRecipe;setupPurchaseSelection();
}
function setupPurchaseSelection(){const label=$('showPurchased').closest('.check-filter'),actions=document.createElement('div');actions.className='header-actions';const b=document.createElement('button');b.id='applyShoppingPurchase';b.type='button';b.className='primary-button';b.textContent='購入を反映';b.disabled=true;actions.appendChild(b);label.parentElement.appendChild(actions);actions.appendChild(label);$('shoppingList').addEventListener('change',e=>{const input=e.target.closest('.purchase-check');if(!input)return;e.preventDefault();e.stopImmediatePropagation();const id=input.dataset.id,item=state.shoppingList.find(x=>x.id===id);if(!item)return;if(input.checked===item.is_purchased)state.shoppingPendingChanges.delete(id);else state.shoppingPendingChanges.set(id,input.checked);updatePurchaseButton()},true);b.onclick=commitPurchaseChanges}
function updatePurchaseButton(){const b=$('applyShoppingPurchase');if(!b)return;const n=state.shoppingPendingChanges.size;b.disabled=!n;b.textContent=n?`購入を反映（${n}件）`:'購入を反映'}
async function commitPurchaseChanges(){const changes=[...state.shoppingPendingChanges.entries()];if(!changes.length)return;if(!confirm(`${changes.length}件の購入状態を反映しますか？`))return;loading(true);try{for(const[id,next]of changes){const item=state.shoppingList.find(x=>x.id===id);if(!item){state.shoppingPendingChanges.delete(id);continue}if(next&&!item.is_purchased){const at=new Date().toISOString();const{error:hErr}=await supabase.from('shopping_purchase_history').insert({shopping_list_item_id:id,name:item.name,category:item.category,master_id:item.master_id,purchased_at:at});if(hErr)throw hErr;const{error:e}=await supabase.from('shopping_list_items').update({is_purchased:true,purchased_at:at,updated_at:new Date().toISOString()}).eq('id',id);if(e)throw e}else if(!next&&item.is_purchased){if(item.purchased_at){const{data:h}=await supabase.from('shopping_purchase_history').select('id').eq('shopping_list_item_id',id).eq('purchased_at',item.purchased_at).maybeSingle();if(h)await supabase.from('shopping_purchase_history').delete().eq('id',h.id)}const{error:e}=await supabase.from('shopping_list_items').update({is_purchased:false,purchased_at:null,updated_at:new Date().toISOString()}).eq('id',id);if(e)throw e}state.shoppingPendingChanges.delete(id)}await loadShopping();toast('購入状態を反映しました')}catch(e){toast(`購入状態を反映できませんでした: ${e.message}`)}finally{loading(false)}}
async function loadTags(){const{data,error}=await supabase.from('tags').select('id,name').order('name');if(error)throw error;state.tags=data||[];fillSelect($('tagFilter'),state.tags.map(x=>x.name),'タグすべて')}
async function loadRecipes(){const{data,error}=await supabase.from('recipes').select('*,recipe_ingredients(*),recipe_tags(tag_id,tags(id,name))').order('updated_at',{ascending:false});if(error)throw error;state.recipes=data||[];renderList()}
function recipeTags(r){return(r.recipe_tags||[]).map(x=>x.tags).filter(Boolean)}
function renderList(){const q=$('searchInput').value.trim().toLowerCase(),cat=$('categoryFilter').value,genre=$('genreFilter').value,tag=$('tagFilter').value,fav=$('favoriteFilter').checked;const rows=state.recipes.filter(r=>(!q||`${r.name} ${(r.recipe_ingredients||[]).map(i=>i.ingredient_name).join(' ')}`.toLowerCase().includes(q))&&(!cat||r.cooking_category===cat)&&(!genre||r.genre===genre)&&(!tag||recipeTags(r).some(t=>t.name===tag))&&(!fav||r.is_favorite));$('recipeList').innerHTML=rows.length?rows.map(r=>`<article class="recipe-item" data-id="${r.id}"><div class="recipe-item-top"><div><h3>${esc(r.name)}</h3><div class="meta">${esc(r.cooking_category)} ・ ${esc(r.genre)}</div></div><div class="favorite">${r.is_favorite?'★':''}</div></div>${r.description?`<p class="meta">${esc(r.description)}</p>`:''}<div class="tags">${recipeTags(r).map(t=>`<span class="tag">${esc(t.name)}</span>`).join('')}</div></article>`).join(''):'<div class="empty">レシピがありません。<br>「＋ レシピ登録」から登録できます。</div>';document.querySelectorAll('.recipe-item').forEach(e=>e.onclick=()=>openDetail(e.dataset.id))}
function resetIngredientRows(items=[{}]){$('ingredientRows').innerHTML='';items.forEach(addIngredientRow)}
function addIngredientRow(item={}){const r=document.createElement('div');r.className='ingredient-row';r.innerHTML=`<input class="ingredient-name" placeholder="材料名" value="${esc(item.ingredient_name||'')}"><input class="ingredient-amount" placeholder="分量" value="${esc(item.amount||'')}"><input class="ingredient-unit" placeholder="単位" value="${esc(item.unit||'')}"><input class="ingredient-note" placeholder="メモ（下味など）" value="${esc(item.note||'')}"><button type="button" class="remove-button">削除</button>`;r.querySelector('.remove-button').onclick=()=>{r.remove();if(!$('ingredientRows').children.length)addIngredientRow()};$('ingredientRows').appendChild(r)}
function resetInstructions(items=['']){$('instructionRows').innerHTML='';items.forEach(addInstructionRow)}
function addInstructionRow(text=''){const r=document.createElement('div');r.className='instruction-row';r.innerHTML=`<span class="instruction-number"></span><textarea rows="2" placeholder="作り方を入力">${esc(text)}</textarea><button type="button" class="remove-button">削除</button>`;r.querySelector('.remove-button').onclick=()=>{r.remove();renumberInstructions()};$('instructionRows').appendChild(r);renumberInstructions()}
function renumberInstructions(){[...$('instructionRows').children].forEach((r,i)=>r.querySelector('.instruction-number').textContent=i+1)}
function renderTagChoices(selected=[]){$('tagChoices').innerHTML=state.tags.map(t=>`<button type="button" class="tag-choice ${selected.includes(t.id)?'selected':''}" data-tag="${t.id}">${esc(t.name)}</button>`).join('');document.querySelectorAll('.tag-choice').forEach(b=>b.onclick=()=>b.classList.toggle('selected'))}
async function openForm(id=null){state.editingId=id;$('formTitle').textContent=id?'レシピ編集':'レシピ登録';if(!id){$('recipeForm').reset();resetIngredientRows();resetInstructions();renderTagChoices();view('formView');return}loading(true);try{const r=state.recipes.find(x=>x.id===id)||await fetchRecipe(id);$('recipeForm').elements.name.value=r.name||'';$('recipeForm').elements.description.value=r.description||'';$('formCategory').value=r.cooking_category;$('formGenre').value=r.genre;$('recipeForm').elements.is_favorite.checked=!!r.is_favorite;$('recipeForm').elements.make_again.checked=!!r.make_again;$('recipeForm').elements.memo.value=r.memo||'';resetIngredientRows(r.recipe_ingredients||[]);resetInstructions(Array.isArray(r.instructions)?r.instructions:[]);renderTagChoices(recipeTags(r).map(t=>t.id));view('formView')}catch(e){toast(e.message)}finally{loading(false)}}
async function fetchRecipe(id){const{data,error}=await supabase.from('recipes').select('*,recipe_ingredients(*),recipe_tags(tag_id,tags(id,name))').eq('id',id).single();if(error)throw error;return data}
async function saveRecipe(e){e.preventDefault();const f=$('recipeForm'),ingredients=[...document.querySelectorAll('.ingredient-row')].map(r=>({ingredient_name:r.querySelector('.ingredient-name').value.trim(),amount:r.querySelector('.ingredient-amount').value.trim()||null,unit:r.querySelector('.ingredient-unit').value.trim()||null,note:r.querySelector('.ingredient-note').value.trim()||null})).filter(x=>x.ingredient_name),instructions=[...document.querySelectorAll('.instruction-row textarea')].map(x=>x.value.trim()).filter(Boolean),tagIds=[...document.querySelectorAll('.tag-choice.selected')].map(x=>x.dataset.tag);const base={name:f.elements.name.value.trim(),description:f.elements.description.value.trim()||null,cooking_category:f.elements.cooking_category.value,genre:f.elements.genre.value,instructions,is_favorite:f.elements.is_favorite.checked,make_again:f.elements.make_again.checked,memo:f.elements.memo.value.trim()||null};if(!base.name){toast('レシピ名を入力してください');return}loading(true);try{let id=state.editingId;if(id){const{error}=await supabase.from('recipes').update(base).eq('id',id);if(error)throw error}else{const{data,error}=await supabase.from('recipes').insert(base).select('id').single();if(error)throw error;id=data.id}let r=await supabase.from('recipe_ingredients').delete().eq('recipe_id',id);if(r.error)throw r.error;if(ingredients.length){r=await supabase.from('recipe_ingredients').insert(ingredients.map((x,i)=>({...x,recipe_id:id,sort_order:i})));if(r.error)throw r.error}r=await supabase.from('recipe_tags').delete().eq('recipe_id',id);if(r.error)throw r.error;if(tagIds.length){r=await supabase.from('recipe_tags').insert(tagIds.map(tag_id=>({recipe_id:id,tag_id})));if(r.error)throw r.error}await loadRecipes();await openDetail(id);toast('保存しました')}catch(e){toast(`保存できませんでした: ${e.message}`)}finally{loading(false)}}
async function openDetail(id){state.detailId=id;loading(true);try{const r=await fetchRecipe(id),tags=recipeTags(r),ings=r.recipe_ingredients||[],ins=Array.isArray(r.instructions)?r.instructions:[];$('recipeDetail').innerHTML=`<div class="detail-header"><h2>${esc(r.name)}</h2><p class="detail-description">${esc(r.description||'')}</p><div class="detail-meta"><span class="tag">${esc(r.cooking_category)}</span><span class="tag">${esc(r.genre)}</span>${tags.map(t=>`<span class="tag">${esc(t.name)}</span>`).join('')}</div><div class="detail-flags">${r.is_favorite?'★ お気に入り':''}${r.make_again?'　↻ また作りたい':''}</div></div><section class="detail-section"><h3>材料</h3><ul class="ingredient-list">${ings.map(i=>`<li><span>${esc(i.ingredient_name)}</span><span>${esc([i.amount,i.unit].filter(Boolean).join(' '))}</span><span>${esc(i.note||'')}</span></li>`).join('')||'<li class="no-data">材料なし</li>'}</ul></section><section class="detail-section"><h3>作り方</h3><ol class="instruction-list">${ins.map(i=>`<li>${esc(i)}</li>`).join('')||'<li class="no-data">手順なし</li>'}</ol></section>${r.memo?`<section class="detail-section"><h3>メモ</h3><div class="memo">${esc(r.memo)}</div></section>`:''}`;view('detailView')}catch(e){toast(e.message)}finally{loading(false)}}
async function deleteCurrentRecipe(){if(!state.detailId||!confirm('このレシピを削除しますか？'))return;loading(true);try{const{error}=await supabase.from('recipes').delete().eq('id',state.detailId);if(error)throw error;state.detailId=null;await loadRecipes();view('listView');toast('削除しました')}catch(e){toast(`削除できませんでした: ${e.message}`)}finally{loading(false)}}
async function ensureShoppingMaster(){const{data,error}=await supabase.from('shopping_master').select('id').limit(1);if(error)throw error;if(data?.length)return;const rows=DEFAULT_SHOPPING_MASTER.flatMap(([cat,names],ci)=>names.map((name,i)=>({name,category:cat,sort_order:ci*100+i})));const{error:e}=await supabase.from('shopping_master').upsert(rows,{onConflict:'user_id,name',ignoreDuplicates:true});if(e)throw e}
async function loadShopping(){await ensureShoppingMaster();const[{data:m,error:me},{data:l,error:le}]=await Promise.all([supabase.from('shopping_master').select('*').eq('is_active',true).order('sort_order'),supabase.from('shopping_list_items').select('*').order('created_at',{ascending:true})]);if(me)throw me;if(le)throw le;state.shoppingMaster=m||[];state.shoppingList=l||[];renderShoppingMaster();renderShoppingList()}
function renderShoppingMaster(){const selected=new Set([...document.querySelectorAll('.shopping-master-check:checked')].map(x=>x.dataset.id));$('shoppingMaster').innerHTML=SHOPPING_CATEGORIES.map(cat=>{const items=state.shoppingMaster.filter(x=>x.category===cat);if(!items.length)return '';return `<section class="shopping-category"><h3>${esc(cat)}</h3><div class="shopping-master-items">${items.map(x=>`<label class="shopping-master-item-wrap"><span class="shopping-master-item"><input class="shopping-master-check" type="checkbox" data-id="${x.id}" ${selected.has(x.id)?'checked':''}><span>${esc(x.name)}</span></span></label>`).join('')}</div></section>`}).join('')}
async function addShoppingMasterItem(e){e.preventDefault();const name=$('shoppingMasterInputName').value.trim(),category=$('shoppingMasterInputCategory').value;if(!name)return;if(state.shoppingMaster.some(x=>x.name===name)){toast('その商品はすでに登録されています');return}loading(true);try{const{error}=await supabase.from('shopping_master').insert({name,category,sort_order:state.shoppingMaster.length});if(error)throw error;$('shoppingMasterInputName').value='';await loadShopping();toast('よく買うものに追加しました')}catch(e){toast(`追加できませんでした: ${e.message}`)}finally{loading(false)}}
async function addSelectedShoppingItems(){const inputs=[...document.querySelectorAll('.shopping-master-check:checked')];if(!inputs.length){toast('追加する商品を選択してください');return}const ids=inputs.map(x=>x.dataset.id),existing=new Set(state.shoppingList.filter(x=>!x.is_purchased).map(x=>x.name)),rows=state.shoppingMaster.filter(x=>ids.includes(x.id)&&!existing.has(x.name)).map(x=>({master_id:x.id,name:x.name,category:x.category,is_purchased:false}));if(!rows.length){toast('選択した商品はすでに買い物リストにあります');return}loading(true);try{const{error}=await supabase.from('shopping_list_items').insert(rows);if(error)throw error;await loadShopping();toast(`${rows.length}件を買い物リストに追加しました`)}catch(e){toast(`追加できませんでした: ${e.message}`)}finally{loading(false)}}
async function addFreeShoppingItem(e){e.preventDefault();const name=$('shoppingInputName').value.trim(),category=$('shoppingInputCategory').value;if(!name)return;if(state.shoppingList.some(x=>!x.is_purchased&&x.name===name)){toast('その商品はすでに買い物リストにあります');return}loading(true);try{const{error}=await supabase.from('shopping_list_items').insert({name,category,is_purchased:false});if(error)throw error;$('shoppingInputName').value='';await loadShopping();toast('買い物リストに追加しました')}catch(e){toast(`追加できませんでした: ${e.message}`)}finally{loading(false)}}
function renderShoppingList(){const list=[...state.shoppingList].sort((a,b)=>a.is_purchased!==b.is_purchased?(a.is_purchased?1:-1):new Date(a.created_at)-new Date(b.created_at)),visible=state.showPurchased?list:list.filter(x=>!x.is_purchased),p=list.filter(x=>x.is_purchased).length;$('shoppingListSummary').textContent=list.length?`${list.length}件（未購入 ${list.length-p}件・購入済み ${p}件）`:'まだ商品がありません';$('shoppingList').innerHTML=visible.length?visible.map(x=>{const pending=state.shoppingPendingChanges.get(x.id),checked=pending!==undefined?pending:x.is_purchased;return `<div class="shopping-list-item ${x.is_purchased?'purchased':''}"><label class="shopping-list-check"><input type="checkbox" class="purchase-check" data-id="${x.id}" ${checked?'checked':''}><span>${esc(x.name)}</span></label><span class="shopping-list-category">${esc(x.category)}</span><span class="shopping-purchased-date">${x.is_purchased&&x.purchased_at?`購入日 ${esc(new Date(x.purchased_at).toLocaleDateString('ja-JP'))}`:''}</span><button type="button" class="remove-button shopping-delete" data-id="${x.id}">削除</button></div>`}).join(''):`<div class="empty">${list.length?'購入済みの商品はありません。':'買い物リストは空です。'}</div>`;document.querySelectorAll('.shopping-delete').forEach(b=>b.onclick=()=>deleteShoppingItem(b.dataset.id));updatePurchaseButton()}
async function deleteShoppingItem(id){if(!confirm('この商品を買い物リストから削除しますか？'))return;loading(true);try{const{error}=await supabase.from('shopping_list_items').delete().eq('id',id);if(error)throw error;state.shoppingPendingChanges.delete(id);await loadShopping();toast('削除しました')}catch(e){toast(`削除できませんでした: ${e.message}`)}finally{loading(false)}}
async function openShopping(){loading(true);try{await loadShopping();view('shoppingView')}catch(e){toast(`買い物データを読み込めませんでした: ${e.message}`)}finally{loading(false)}}
async function init(){setup();loading(true);try{await ensureAuth();await loadTags();await loadRecipes()}catch(e){console.error(e);toast(`初期化できませんでした: ${e.message}`)}finally{loading(false)}}
init();
