import { supabase } from './supabase.js?v=20261007-3';

const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let stores = [];
let activePurchaseRows = [];
const UNIT_OPTIONS = [['g','g'],['kg','kg'],['ml','ml'],['L','L'],['個','個'],['枚','枚'],['本','本'],['その他','その他']];
const unitOptionsHtml = selected => UNIT_OPTIONS.map(([value,label]) => `<option value="${value}"${selected===value?' selected':''}>${label}</option>`).join('');

function addStyles(){
  if(document.getElementById('shoppingPriceStyles')) return;
  const s=document.createElement('style'); s.id='shoppingPriceStyles'; s.textContent=`
    .sp-modal-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.42);z-index:1000;display:flex;align-items:flex-start;justify-content:center;padding:20px 12px;overflow:auto}
    .sp-modal{width:min(680px,100%);background:#fff;border-radius:16px;padding:20px;box-shadow:0 16px 50px rgba(0,0,0,.22)}
    .sp-modal h3{margin:0 0 6px}.sp-modal .meta{margin:0 0 16px}.sp-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:16px;flex-wrap:wrap}.sp-actions button{min-height:42px}
    .sp-grid{display:grid;gap:12px}.sp-field{display:grid;gap:6px}.sp-field label{font-weight:600}.sp-field input,.sp-field select{width:100%;box-sizing:border-box}
    .sp-purchase-row{border:1px solid #ddd;border-radius:12px;padding:12px;margin:10px 0}.sp-purchase-title{font-weight:700;margin-bottom:10px}.sp-purchase-fields{display:grid;grid-template-columns:1fr 1fr;gap:10px}.sp-patterns{margin-top:10px;padding-top:10px;border-top:1px solid #eee}.sp-pattern-label{font-size:.88em;opacity:.75;margin-bottom:6px}.sp-pattern-buttons{display:flex;gap:6px;flex-wrap:wrap}.sp-pattern-button{border:1px solid #ccc;background:#fff;border-radius:999px;padding:6px 10px;cursor:pointer}.sp-pattern-button:hover{background:#f5f5f5}.sp-history-store,.sp-history-price{margin-left:8px}.sp-history-price{font-weight:700}.sp-history-store{font-size:.9em;opacity:.75}
    .sp-history-unit-price{margin-left:8px;font-size:.9em;opacity:.8}.sp-store-list{display:grid;gap:8px;margin-top:12px}.sp-store-item{display:flex;align-items:center;justify-content:space-between;gap:8px;border:1px solid #ddd;border-radius:10px;padding:10px}.sp-store-actions{display:flex;gap:6px}
    @media(max-width:520px){.sp-purchase-fields{grid-template-columns:1fr}}
  `; document.head.appendChild(s);
}
function modal(html){const b=document.createElement('div');b.className='sp-modal-backdrop';b.innerHTML=`<div class="sp-modal" role="dialog" aria-modal="true">${html}</div>`;document.body.appendChild(b);return b}
function closeModal(b){b?.remove()}
async function loadStores(){const{data,error}=await supabase.from('shopping_stores').select('*').eq('is_active',true).order('name');if(error)throw error;stores=data||[];return stores}
async function openStoreManager(){
  addStyles(); await loadStores();
  const b=modal(`<h3>店舗管理</h3><p class="meta">購入記録で使う店舗を登録します。</p><form id="spStoreForm" class="sp-grid"><div class="sp-field"><label>店舗名</label><input name="name" required maxlength="100" placeholder="例：ロピア 茅ヶ崎店"></div><div class="sp-field"><label>住所（任意）</label><input name="address" maxlength="200" placeholder="例：茅ヶ崎市○○"></div><div class="sp-field"><label>店舗カテゴリ（任意）</label><input name="store_category" maxlength="50" placeholder="例：スーパー"></div><div class="sp-actions"><button type="button" id="spStoreClose" class="secondary-button">閉じる</button><button type="submit" class="primary-button">店舗を登録</button></div></form><div class="sp-store-list" id="spStoreList"></div>`);
  const list=b.querySelector('#spStoreList');
  const render=()=>{list.innerHTML=stores.length?stores.map(s=>`<div class="sp-store-item"><div><strong>${esc(s.name)}</strong>${s.address?`<div class="meta">${esc(s.address)}</div>`:''}</div><div class="sp-store-actions"><button type="button" class="secondary-button sp-store-edit" data-id="${s.id}">編集</button><button type="button" class="danger-button sp-store-delete" data-id="${s.id}">非表示</button></div></div>`).join(''):'<div class="empty">登録店舗はありません。</div>'};render();
  b.querySelector('#spStoreClose').onclick=()=>closeModal(b);
  b.querySelector('#spStoreForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,v={name:f.elements.name.value.trim(),address:f.elements.address.value.trim()||null,store_category:f.elements.store_category.value.trim()||null};if(!v.name)return;const{error}=await supabase.from('shopping_stores').insert(v);if(error){alert(`登録できませんでした: ${error.message}`);return}await loadStores();f.reset();render()};
  list.addEventListener('click',async e=>{const btn=e.target.closest('button');if(!btn)return;const id=btn.dataset.id,s=stores.find(x=>x.id===id);if(!s)return;if(btn.classList.contains('sp-store-delete')){if(!confirm(`「${s.name}」を店舗一覧から非表示にしますか？\n購入履歴は残ります。`))return;const{error}=await supabase.from('shopping_stores').update({is_active:false,updated_at:new Date().toISOString()}).eq('id',id);if(error){alert(`変更できませんでした: ${error.message}`);return}await loadStores();render()}else{const name=prompt('店舗名',s.name);if(name===null)return;const address=prompt('住所（任意）',s.address||'');const category=prompt('店舗カテゴリ（任意）',s.store_category||'');const{error}=await supabase.from('shopping_stores').update({name:name.trim()||s.name,address:address?.trim()||null,store_category:category?.trim()||null,updated_at:new Date().toISOString()}).eq('id',id);if(error){alert(`更新できませんでした: ${error.message}`);return}await loadStores();render()}});
}
async function getCurrentItems(ids){const{data,error}=await supabase.from('shopping_list_items').select('*').in('id',ids);if(error)throw error;return data||[]}
async function loadPurchasePatterns(names){
  if(!names.length)return new Map();
  const{data,error}=await supabase.from('shopping_purchase_history').select('name,quantity,unit,specification,purchased_at').in('name',names).order('purchased_at',{ascending:false});
  if(error)throw error;
  const map=new Map();
  (data||[]).forEach(x=>{if(!map.has(x.name))map.set(x.name,[]);const arr=map.get(x.name);const key=`${x.quantity}|${x.unit||''}|${x.specification||''}`;if(!arr.some(p=>p.key===key))arr.push({key,quantity:x.quantity,unit:x.unit||'',specification:x.specification||''})});
  return map;
}
async function findOrCreateProduct(item,specification,unit){
  const un=unit?.trim()||null, spec=specification?.trim()||null;
  let q=supabase.from('shopping_products').select('*').eq('name',item.name).eq('household_id','22222222-2222-2222-2222-222222222222');
  q=spec===null?q.is('specification',null):q.eq('specification',spec); q=un===null?q.is('unit',null):q.eq('unit',un);
  const{data,error}=await q.maybeSingle(); if(error)throw error; if(data)return data;
  const{data:created,error:e}=await supabase.from('shopping_products').insert({name:item.name,category:item.category,specification:spec,unit:un}).select('*').single(); if(e)throw e; return created;
}
function unitBasePrice(price,quantity,unit){const p=Number(price),q=Number(quantity);if(!Number.isFinite(p)||!Number.isFinite(q)||q<=0)return null;switch(unit){case'kg':case'g':case'L':case'ml':return p/q*100;case'個':case'枚':case'本':return p/q;default:return null}}
function baseUnitLabel(unit){switch(unit){case'g':case'kg':return'100g';case'ml':case'L':return'100ml';case'個':return'1個';case'枚':return'1枚';case'本':return'1本';default:return null}}
function patternLabel(p){const q=p.quantity??'';const u=p.unit||'';const spec=p.specification||'タイプ未設定';return `${q}${u}・${spec}`}
async function openPurchaseModal(items){
  await loadStores(); if(!stores.length){alert('購入記録の前に店舗を1件登録してください。');await openStoreManager();return false}
  const patterns=await loadPurchasePatterns(items.map(x=>x.name));
  const b=modal(`<h3>購入内容を記録</h3><p class="meta">店舗と実際の価格、内容量を入力してください。過去の購入パターンは自動で候補に出ます。</p><div class="sp-field"><label>購入店舗</label><div style="display:flex;gap:8px"><select id="spStoreSelect" style="flex:1"><option value="">店舗を選択</option>${stores.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select><button type="button" id="spManageStores" class="secondary-button">店舗管理</button></div></div><div id="spPurchaseRows"></div><div class="sp-actions"><button type="button" id="spPurchaseCancel" class="secondary-button">キャンセル</button><button type="button" id="spPurchaseSave" class="primary-button">購入を記録</button></div>`);
  const rows=b.querySelector('#spPurchaseRows');
  activePurchaseRows=items.map(item=>({item,patterns:patterns.get(item.name)||[]}));
  rows.innerHTML=activePurchaseRows.map((r,i)=>{const first=r.patterns[0]||{};return `<div class="sp-purchase-row"><div class="sp-purchase-title">${esc(r.item.name)}</div><div class="sp-purchase-fields"><div class="sp-field"><label>価格（税込）</label><input class="sp-price" data-i="${i}" type="number" min="0" step="1" inputmode="numeric" required placeholder="例：238"></div><div class="sp-field"><label>内容量</label><div style="display:grid;grid-template-columns:1fr 120px;gap:8px"><input class="sp-quantity" data-i="${i}" type="number" min="0.001" step="0.001" inputmode="decimal" required value="${esc(first.quantity||'')}" placeholder="例：500"><select class="sp-unit" data-i="${i}" required><option value="">単位を選択</option>${unitOptionsHtml(first.unit||'')}</select></div></div></div><div class="sp-field" style="margin-top:10px"><label>商品タイプ（任意）</label><input class="sp-specification" data-i="${i}" type="text" maxlength="100" value="${esc(first.specification||'')}" placeholder="例：大玉、赤玉・Lサイズ"></div>${r.patterns.length?`<div class="sp-patterns"><div class="sp-pattern-label">過去の入力</div><div class="sp-pattern-buttons">${r.patterns.map((p,pi)=>`<button type="button" class="sp-pattern-button" data-i="${i}" data-key="${esc(p.key)}">${esc(patternLabel(p))}</button>`).join('')}</div></div>`:''}</div>`}).join('');
  const refreshPatternButtons=i=>{const r=activePurchaseRows[i];const qty=Number(b.querySelector(`.sp-quantity[data-i="${i}"]`)?.value);const unit=b.querySelector(`.sp-unit[data-i="${i}"]`)?.value;const candidates=r.patterns.filter(p=>(!unit||p.unit===unit)&&(!qty||Number(p.quantity)===qty));const all=r.patterns.filter(p=>!unit||p.unit===unit);const use=candidates.length?candidates:all;const wrap=b.querySelector(`.sp-purchase-row:nth-child(${i+1}) .sp-pattern-buttons`);if(!wrap)return;wrap.innerHTML=use.map(p=>`<button type="button" class="sp-pattern-button" data-i="${i}" data-key="${esc(p.key)}">${esc(patternLabel(p))}</button>`).join('');};
  rows.addEventListener('click',e=>{const btn=e.target.closest('.sp-pattern-button');if(!btn)return;const i=Number(btn.dataset.i),r=activePurchaseRows[i],p=r.patterns.find(x=>x.key===btn.dataset.key);if(!p)return;b.querySelector(`.sp-quantity[data-i="${i}"]`).value=p.quantity??'';b.querySelector(`.sp-unit[data-i="${i}"]`).value=p.unit||'';b.querySelector(`.sp-specification[data-i="${i}"]`).value=p.specification||'';refreshPatternButtons(i)});
  activePurchaseRows.forEach((r,i)=>{b.querySelector(`.sp-quantity[data-i="${i}"]`)?.addEventListener('input',()=>refreshPatternButtons(i));b.querySelector(`.sp-unit[data-i="${i}"]`)?.addEventListener('change',()=>refreshPatternButtons(i))});
  b.querySelector('#spPurchaseCancel').onclick=()=>closeModal(b); b.querySelector('#spManageStores').onclick=async()=>{closeModal(b);await openStoreManager()};
  b.querySelector('#spPurchaseSave').onclick=async()=>{const storeId=b.querySelector('#spStoreSelect').value;if(!storeId){alert('購入店舗を選択してください。');return}const entries=activePurchaseRows.map((r,i)=>({r,price:b.querySelector(`.sp-price[data-i="${i}"]`).value,quantity:b.querySelector(`.sp-quantity[data-i="${i}"]`).value,unit:b.querySelector(`.sp-unit[data-i="${i}"]`).value,specification:b.querySelector(`.sp-specification[data-i="${i}"]`).value.trim()||null}));if(entries.some(x=>x.price===''||Number(x.price)<0||!x.quantity||Number(x.quantity)<=0||!x.unit)){alert('価格・内容量・単位を確認してください。');return}const now=new Date().toISOString();try{for(const x of entries){const p=await findOrCreateProduct(x.r,x.specification,x.unit);const historyPayload={shopping_list_item_id:x.r.id,product_id:p.id,store_id:storeId,quantity:Number(x.quantity),purchase_price:Number(x.price),specification:x.specification,unit:x.unit,name:x.r.name,category:x.r.category,purchased_at:now};const{data:existingHistory,error:findHistoryError}=await supabase.from('shopping_purchase_history').select('id').eq('shopping_list_item_id',x.r.id).maybeSingle();if(findHistoryError)throw findHistoryError;let historyError;if(existingHistory?.id){const{error}=await supabase.from('shopping_purchase_history').update(historyPayload).eq('id',existingHistory.id);historyError=error}else{const{error}=await supabase.from('shopping_purchase_history').insert(historyPayload);historyError=error}if(historyError)throw historyError;const{error:uErr}=await supabase.from('shopping_list_items').update({product_id:p.id,is_purchased:true,purchased_at:now,updated_at:now}).eq('id',x.r.id);if(uErr)throw uErr}closeModal(b);toastCompat('購入価格を記録しました。');setTimeout(()=>location.reload(),250)}catch(e){alert(`購入記録を保存できませんでした: ${e.message}`)}};
  return true;
}
function toastCompat(msg){const t=document.getElementById('toast');if(!t)return;t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2200)}
async function handlePurchaseApply(e){const button=e.target.closest('#applyShoppingPurchase');if(!button)return;const checks=[...document.querySelectorAll('#shoppingList .purchase-check')];if(!checks.length)return;const ids=checks.map(x=>x.dataset.id),items=await getCurrentItems(ids),byId=new Map(items.map(x=>[x.id,x])),purchases=checks.filter(x=>x.checked&&!byId.get(x.dataset.id)?.is_purchased).map(x=>byId.get(x.dataset.id)).filter(Boolean);if(!purchases.length)return;e.preventDefault();e.stopImmediatePropagation();await openPurchaseModal(purchases)}
function renderBasePrice(price,quantity,unit){const v=unitBasePrice(price,quantity,unit),label=baseUnitLabel(unit);return v!==null&&label?`<span class="sp-history-unit-price">${v.toLocaleString('ja-JP',{maximumFractionDigits:2})}円/${label}</span>`:''}
async function renderEnhancedHistory(){const container=document.getElementById('shoppingHistory');if(!container)return;const{data,error}=await supabase.from('shopping_purchase_history').select('*, shopping_stores(name)').order('purchased_at',{ascending:false});if(error){container.innerHTML=`<div class="empty">履歴を読み込めませんでした。<br>${esc(error.message)}</div>`;return}if(!data?.length){container.innerHTML='<div class="empty">まだ購入履歴がありません。</div>';return}const groups=new Map();data.forEach(x=>{const d=new Date(x.purchased_at),key=`${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`;if(!groups.has(key))groups.set(key,{date:d,items:[]});groups.get(key).items.push(x)});container.innerHTML=[...groups.values()].map(g=>`<section class="shopping-history-day"><h5>${g.date.toLocaleDateString('ja-JP',{year:'numeric',month:'numeric',day:'numeric',weekday:'short'})}</h5><div class="shopping-history-items">${g.items.map(x=>`<div class="shopping-history-item"><div><span class="shopping-history-name">${esc(x.name)}</span><span class="shopping-history-category">${esc(x.category)}</span>${x.shopping_stores?.name?`<span class="sp-history-store">${esc(x.shopping_stores.name)}</span>`:''}${x.purchase_price!==null?`<span class="sp-history-price">${Number(x.purchase_price).toLocaleString('ja-JP')}円</span>${renderBasePrice(x.purchase_price,x.quantity,x.unit)}`:'<span class="sp-history-price">価格未記録</span>'}</div><button type="button" class="remove-button history-delete" data-id="${x.id}">削除</button></div>`).join('')}</div></section>`).join('');container.querySelectorAll('.history-delete').forEach(btn=>btn.onclick=async()=>{if(!confirm('この購入履歴を削除しますか？\n買い物リストの状態は変更しません。'))return;const{error:e}=await supabase.from('shopping_purchase_history').delete().eq('id',btn.dataset.id);if(e){alert(`削除できませんでした: ${e.message}`);return}await renderEnhancedHistory()})}
function wire(){
  addStyles();
  const setup=()=>{
    const apply=document.getElementById('applyShoppingPurchase');
    if(apply&&!apply.dataset.priceWired){apply.dataset.priceWired='1';apply.addEventListener('click',handlePurchaseApply,true)}
    const hb=document.getElementById('shoppingHistoryButton');
    if(hb&&!hb.dataset.priceWired){hb.dataset.priceWired='1';hb.addEventListener('click',async e=>{e.preventDefault();e.stopImmediatePropagation();document.getElementById('shoppingMainContent')?.classList.add('hidden');document.getElementById('shoppingHistorySection')?.classList.remove('hidden');await renderEnhancedHistory()},true)}
    const heading=document.querySelector('.shopping-heading-actions');
    if(heading&&!document.getElementById('shoppingStoreButton')){const b=document.createElement('button');b.id='shoppingStoreButton';b.type='button';b.className='secondary-button';b.textContent='店舗管理';b.onclick=openStoreManager;heading.appendChild(b)}
  };
  setup();
  const observer=new MutationObserver(setup);
  observer.observe(document.body,{childList:true,subtree:true});
}
wire();
